### PR TITLE
17 campaigns should not have responses

### PR DESCRIPTION
**Pull request by leonardk1**
#17

As A Developer
I Want To remove all the methods and logic that was dealing with responses
As it is not a requirement any more
##### tasks
- [x] Remove all methods that were dealing with responses
- [x] ensure that the tests pass after making the changes

### CODE REVIEW

**Comment by arafatm** [comment]
@leonardk1 conflict on this one.

**Comment by leonardk1** [comment]
@arafatm conflict fixed

**Comment by arafatm** [comment]
@leonardk1 thank you

**Comment by leonardk1** [comment]
:+1:

**Pull request merged**
